- platform: rflink
  automatic_add: true
  device_defaults:
    fire_event: true
    # signal_repetitions: 2   
  devices:
    fa500_00005963_01:
      name: Bathroom-433
      type: switchable

- platform: yeelight
  devices:
    192.168.0.206:
      name: Living Room
      transition: 1000
      use_music_mode: True #(defaults to False)
      save_on_change: False #(defaults to True)
        #  - platform: xiaomi_miio
        # name: Xiaomi Philips Smart LED Ball
        # host: 192.168.0.205
        # token: YOUR_TOKEN
 
- platform: template
  lights:
    bathroom:
      friendly_name: "Bathroom"
      value_template: "{{ is_state('switch.wall_switch_right_158d0001f51199', 'on') }}"
      turn_on:
        service: switch.turn_on
        entity_id: switch.wall_switch_right_158d0001f51199
      turn_off:
        service: switch.turn_off
        entity_id: switch.wall_switch_right_158d0001f51199
    hallway:
      friendly_name: "Hallway"
      value_template: "{{ is_state('switch.wall_switch_left_158d0001f51199', 'on') }}"
      turn_on:
        service: switch.turn_on
        entity_id: switch.wall_switch_left_158d0001f51199
      turn_off:
        service: switch.turn_off
        entity_id: switch.wall_switch_left_158d0001f51199

