- platform: yr
  name: Weather
  forecast: 24
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - pressure
    - windDirection
    - humidity
      #- fog
      #- cloudiness
      #- lowClouds
      #- mediumClouds
      #- highClouds
      #- dewpointTemperature

- platform: rflink
  automatic_add: true
  devices:
    alectov4_59e8_temp:
      name: Outside temperature
      sensor_type: temperature
      # state_topic: sensor/outside/temperature
      unit_of_measurement: "°C"
    alectov4_59e8_hum:
      name: Outside humidty
      sensor_type: humidity
      # state_topic: sensor/basement/humidity
      unit_of_measurement: "%"

- platform: darksky
  api_key: !secret darksky_api_key
  latitude: 52.091499
  longitude: 5.117643
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance     
    - precip_type
    - precip_intensity
    - precip_probability
    - temperature
    - apparent_temperature
    - dew_point
    - wind_bearing
    - wind_speed
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - wind_bearing
    - precip_intensity_max
    - temperature_max
    - temperature_min
    - apparent_temperature_max
    - apparent_temperature_min
    - hourly_summary
    - minutely_summary
    - daily_summary
    - nearest_storm_distance
    - nearest_storm_bearing
  update_interval: '00:07'

- platform: buienradar
  # name: 'home'
  # Force 'Meetstation Volkel' to be used:
  latitude: 52.091499
  longitude: 5.117643
  monitored_conditions:
    - stationname
    - conditioncode
    - condition
    - conditiondetailed
    - conditionexact
    - symbol
    - humidity
    - temperature
    - groundtemperature
    - windspeed
    - windforce
    - winddirection
    - windazimuth
    - pressure
    - visibility
    - windgust     
    - precipitation
    - irradiance
    - precipitation_forecast_average
    - precipitation_forecast_total
    # conditions for forecasted data:
    #- symbol_1d
    #- symbol_2d
    #- symbol_3d
    #- symbol_4d
    #- symbol_5d
    #- temperature_1d
    #- temperature_2d
    #- temperature_3d
    #- temperature_4d
    #- temperature_5d
    #- rainchance_1d
    #- rainchance_2d
    #- rainchance_3d
    #- rainchance_4d
    #- rainchance_5d
    #- sunchance_1d
    #- sunchance_2d
    #- sunchance_3d
    #- sunchance_4d
    #- sunchance_5d
    #- rain_1d
    #- rain_2d
    #- rain_3d
    #- rain_4d
    #- rain_5d
