- alias: Turn on bathroom light normal - movement
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_occupied
    to: 'on'
  condition:
    condition: time
    after: '06:00:00'
    before: '22:59:00'
  action:
    service: switch.turn_on
    entity_id: switch.wall_switch_right_158d0001f51199


- alias: Turn off bathroom light 1 minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_occupied
    to: 'off'
    for:
      minutes: 1
  action:
    service: switch.turn_off
    entity_id: switch.wall_switch_right_158d0001f51199

